name: Testing for Solo Luxury
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm ci
    #- name: Run all tests
    #  run: npm run wdio
    - name: Run Sign Up tests
      run: npm run test-signup
    - name: Run Login tests
      run: npm run test-login
    - name: Run Password Recovery tests
      run: npm run test-recovery
    - name: Run Search tests
      run: npm run test-search
    - name: Run Search Results tests
      run: npm run test-searchresults
    - name: Run Special Request tests
      run: npm run test-request  
    - uses: actions/checkout@v2
      if: always()
      with:
        repository: txt2021/Solo_Luxury_Autotests
        ref:  report
        path: ./docs
    - name: Generate Allure Report
      if: always()
      run: npm run report-generate
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: report
        path: allure-report/
        retention-days: 30
    - name: Push to repository
      uses: cpina/github-action-push-to-another-repository@main
      if: always()
      env:
        API_TOKEN_GITHUB: ${{ secrets.ACTIONS_TOKEN }}
      with:
        source-directory: 'allure-report'
        destination-github-username: 'txt2021'
        destination-repository-name: 'Solo_Luxury_Autotests'
        user-email: txt2021@gmail.com
        target-branch: report




